import React from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import BookmarkCard from "../components/BookmarkCard";
import PostCard from "../components/PostCard";
import axios from "axios";
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from "reactstrap";

export default function Bookmark(props) {
  const [modal, setModal] = React.useState(false);
  const [singleContent, setSingleContent] = React.useState(null);

  const toggle = (item) => {
    setSingleContent(item); // setSingleContet(item)
    setModal(!modal);
  };

  return (
    <>
      <Head>
        <title>Your Bookmark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal isOpen={modal} toggle={toggle} >
        <ModalHeader toggle={toggle}>Modal title</ModalHeader>
        <ModalBody>
          {singleContent !== null ? (
            <PostCard
              title={singleContent.title}
              image={singleContent.urlToImage}
              content={singleContent.content}
              date={singleContent.publishedAt}
            />
          ) : null}
        </ModalBody>

        <ModalFooter>
          <Button color="primary" onClick={toggle}>
            Do Something
          </Button>{" "}
          <Button color="secondary" onClick={toggle}>
            Cancel
          </Button>
        </ModalFooter>
      </Modal>
      <Layout title="Bookmarks">
        <div className="all-catagory-wrapper">
          <div className="container">
            <h5 className="mb-3 newsten-title">For you</h5>
          </div>
          <div className="container">
            <div className="row">
              {props.news.map((item) => {
                return (
                  <BookmarkCard
                    key={item.url}
                    title={item.title}
                    image={item.urlToImage}
                    showModal={() => toggle(item)}
                  />
                );
              })}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
 
  const trial = async () => {
    let result = await axios.get(
      `https://t1ti0k29ig.execute-api.us-east-1.amazonaws.com/dev/?pagesize=10&page=1`
    );
    return result.data;
  };
  const config = await trial();
  const news = config.message.articles;
  return {
    props: {
      news,
      // categories,
    },
  };
}
