import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Category from "../components/Category";

import slide3 from "../assets/img/bg-img/3.jpg";
import slide4 from "../assets/img/bg-img/4.jpg";
import slide5 from "../assets/img/bg-img/5.jpg";
import slide6 from "../assets/img/bg-img/6.jpg";
import slide7 from "../assets/img/bg-img/7.jpg";
import slide8 from "../assets/img/bg-img/8.jpg";
import slide9 from "../assets/img/bg-img/9.jpg";
import slide10 from "../assets/img/bg-img/10.jpg";
import slide11 from "../assets/img/bg-img/11.jpg";

export default function bookmark() {
  const categories = [
    {
      id: 1,
      category: "Business",
      image: slide3.src,
      url: "/category/business",
      title: "Here we gp again",
    },
    {
      id: 2,
      category: "Politic",
      image: slide7.src,
      url: "/category/politics",
    },
    {
      id: 3,
      category: "Sports",
      image: slide8.src,
      url: "/category/sport",
      title: "Here we gp again",
    },

    {
      id: 4,
      category: "fashion",
      image: slide9.src,
      url: "/category/business",
      title: "Here we gp again",
    },
  ];
  return (
    <>
      <Head>
        <title>Your Bookmark</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Bookmarks">
        <div className="all-catagory-wrapper">
          <div className="container">
            <h5 className="mb-3 newsten-title">For you</h5>
          </div>
          <div className="container">
            <div className="row">
              {categories.map((item) => {
                return (
                  <>
                    <div className="col-6 col-md-4" key={item.id}>
                      <div className="single-recommended-post mt-3">
                        {/* <!-- Customize Button--> */}
                        <div className="bookmark-customize-option">
                          <button
                            className="btn dropdown-toggle"
                            type="button"
                            data-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                          >
                            <i className="lni lni-more"></i>
                          </button>
                          <div className="dropdown-menu dropdown-menu-right">
                            <button className="dropdown-item" type="button">
                              <i className="mr-1 lni lni-cut"></i>Remove
                            </button>
                            <button className="dropdown-item" type="button">
                              <i className="mr-1 lni lni-crop"></i>Edit
                            </button>
                            <button className="dropdown-item" type="button">
                              <i className="mr-1 lni lni-cog"></i>Settings
                            </button>
                          </div>
                        </div>
                        <div className="post-thumbnail">
                          <Image src={item.image} alt="" />
                        </div>
                        <div className="post-content">
                          <a className="post-catagory" href="#">
                            {item.category}
                          </a>
                          <a className="post-title" href={item.url}>
                            {item.title}
                          </a>
                        </div>
                      </div>
                    </div>
                  </>
                );
              })}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
