import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Slide from "../components/Slide";
import SingleCard from "../components/SingleCard";
import CategoryCard from "../components/CategoryCard";
import Category from "../components/Category";
import Link from "next/link";

import slide1 from "../assets/img/bg-img/1.jpg";
import slide2 from "../assets/img/bg-img/2.jpg";
import slide3 from "../assets/img/bg-img/3.jpg";
import slide4 from "../assets/img/bg-img/4.jpg";
import slide5 from "../assets/img/bg-img/5.jpg";
import slide6 from "../assets/img/bg-img/6.jpg";
import slide7 from "../assets/img/bg-img/7.jpg";
import slide8 from "../assets/img/bg-img/8.jpg";
import slide9 from "../assets/img/bg-img/9.jpg";
import slide10 from "../assets/img/bg-img/10.jpg";
import slide11 from "../assets/img/bg-img/11.jpg";
import slide12 from "../assets/img/bg-img/12.jpg";
import slide13 from "../assets/img/bg-img/13.jpg";
import slide14 from "../assets/img/bg-img/14.jpg";
import slide15 from "../assets/img/bg-img/15.jpg";
import slide16 from "../assets/img/bg-img/16.jpg";

export default function Home() {
  const news = [
    {
      id: 1,
      category: "Business",
      title: "The best way to predict the future is to create it",
      date: "July 12, 2019",
      image: slide3.src,
      source: "John Doe",
      url: "https://www.google.com",
    },
    {
      id: 2,
      category: "Politics",
      title: "Let do better than yesterday",
      date: "June 23, 2020",
      image: slide2.src,
      source: "Hans Jame",
      url: "https://www.google.com",
    },
    {
      id: 2,
      category: "Politics",
      title: "Let do better than yesterday",
      date: "June 23, 2020",
      image: slide12.src,
      source: "Hans Jame",
      url: "https://www.google.com",
    },
  ];
  const categories = [
    {
      id: 1,
      category: "Business",
      image: slide3.src,
      url: "/category/business",
    },
    {
      id: 2,
      category: "Politic",
      image: slide7.src,
      url: "/category/politics",
    },
    {
      id: 3,
      category: "Sports",
      image: slide8.src,
      url: "/category/sport",
    },

    {
      id: 4,
      category: "fashion",
      image: slide9.src,
      url: "/category/business",
    },
  ];

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* News slider */}
        <div className="news-today-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between">
              <h5 className="mb-3 pl-1 newsten-title">News Today</h5>
              <p className="mb-3 line-height-1" id="dashboardDate2"></p>
            </div>
            <div className="hero-slides owl-carousel">
              {news.map((item) => {
                return <Slide key={item.id} {...item} />;
              })}
            </div>
          </div>
        </div>
        {/* End of News slider */}

        {/* top categories */}
        <div className="top-catagories-wrapper">
          <div className="bg-shapes">
            {categories.map((item) => {
              return <div className={`shape${item.id}`} key={item.id}></div>;
            })}
          </div>
          <h6 className="mb-3 catagory-title">Top Catagories</h6>
          <div className="container">
            <div className="catagory-slides owl-carousel ">
              {categories.map((item) => {
                return (
                  <div className="single-trending-post d-flex" key={item.id}>
                    <Category {...item} />
                    {/* <CategoryCard key={item.id} image={item.image.src} {...item} /> */}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
        {/* end of top categories */}
        <div className="trending-news-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between mb-3">
              <h5 className="mb-0 pl-1 newsten-title">Trending</h5>
              <Link className="btn btn-primary btn-sm" href="/trending">
                View All
              </Link>
            </div>
          </div>
          <div className="container">
            {/* <!-- Single Trending Post--> */}
            <div className="single-trending-post d-flex">
              <div className="post-thumbnail">
                <Image src={slide4.src} alt="" />
              </div>
              <div className="post-content">
                <Link className="post-title" href="/post">
                  Swimming is a good exercise for the body
                </Link>
                <div className="post-meta d-flex align-items-center">
                  <Link href="/category">Sports</Link>
                  {/* <Link href="#">02 Jun 20</Link> */}
                </div>
              </div>
            </div>
          </div>
        </div>
        {/*  */}
        {/* Popular tag */}
        <div className="popular-tags-wrapper">
          <div className="container">
            <h5 className="mb-3 pl-2 newsten-title">Popular Tags</h5>
          </div>
          <div className="container">
            <div className="popular-tags-list">
              <Link
                className="btn btn-primary btn-sm m-1"
                href="category/politics"
              >
                #Politics
              </Link>
              <Link
                className="btn btn-success btn-sm m-1"
                href="category/fashion"
              >
                #Fashion
              </Link>
              <Link className="btn btn-warning btn-sm m-1" href="category/tech">
                #Tech
              </Link>
              <Link
                className="btn btn-danger btn-sm m-1"
                href="category/lifestyle"
              >
                #Lifestyle
              </Link>
              <Link
                className="btn btn-info btn-sm m-1"
                href="category/sport"
              >
                #Sports
              </Link>
              <Link className="btn btn-success btn-sm m-1" href="category/world">
                #World
              </Link>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
