import React from "react";
import Head from "next/head";
import Image from "next/image";
import slide5 from "../assets/img/bg-img/5.jpg";
import Layout from "../components/Layout";
import Category from "../components/Category";
import Link from "next/link";

export default function post({
  title,
  image,
  category,
  date,
  source,
  url,
  time,
  likes,
  content,
}) {
  return (
    <>
      <Head>
        <title>POST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout title={title}>
        <div id="scrollIndicator"></div>
        <div className="single-blog-thumbnail">
          <Image className="w-100" src={slide5.src} alt="" />
          <Link className="post-bookmark" href="post/bookmark">
            <i className="lni lni-bookmark"></i>
          </Link>
        </div>

        <div className="single-blog-info">
          <div className="container">
            <div className="d-flex align-items-center">
              {/* <!-- Post Like Wrap--> */}
              <div className="post-like-wrap">
                {/* <!-- Favourite Post--> */}
                <div className="post-love d-block">
                  <i className="lni lni-heart"></i>
                </div>
                <span className="d-block">368 Likes</span>
                <div className="line"></div>
                {/* <!-- Share Post--> */}
                <Link
                  className="post-share"
                  href="/post"
                  data-toggle="modal"
                  data-target="#postShareModal"
                >
                  <i className="fa fa-share-alt"></i>
                </Link>
                <span className="d-block">1,028</span>
              </div>
              {/* <!-- Post Content Wrap--> */}
              <div className="post-content-wrap">
                <Link className="post-catagory d-inline-block mb-2" href="category/fashion">
                  Fashion
                </Link>
                <h5 className="mb-2">
                  Jellyfish dont have brains. They dont have a heart, lungs!
                </h5>
                <div className="post-meta">
                  <div className="post-date">
                    23 March
                  </div>
                  <div className="post-views">
                    9,451 Views
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* <!-- Blog Description--> */}
        <div className="blog-description">
          <div className="container">
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Consequatur, id! Accusamus eum deleniti obcaecati sit laboriosam,
              iste iusto? In eveniet fugiat omnis tenetur asperiores nisi
              voluptatem beatae assumenda quas officiis!
            </p>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Exercitationem repudiandae molestiae earum eos voluptatibus nisi
              maxime corrupti repellendus numquam, voluptate labore laudantium,
              commodi sapiente officiis alias. Saepe commodi quidem alias, quam
              ad doloremque iure numquam sequi iste impedit corrupti a sunt!
            </p>
            {/* <div className="embed-responsive embed-responsive-16by9 mb-3">
            {/* <iframe className="embed-responsive-item" src="https://www.youtube.com/embed/9z8ujpPgUjI"></iframe> */}

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum,
              culpa earum. Quaerat, unde laboriosam? Quod, tempora? Quos nobis
              iusto, maiores beatae autem rerum iure ad odio, esse voluptatibus
              omnis, quis ipsum aut minima odit aperiam?
            </p>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam modi
              fuga tenetur labore, rem nam quae tempore, autem numquam sit eius
              et reprehenderit voluptatibus commodi incidunt blanditiis alias
              optio!
            </p>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui
              doloremque distinctio accusantium odit nostrum cum nemo.
              Distinctio veritatis, quibusdam laudantium aperiam corrupti cum
              ducimus libero neque molestiae! Tempora quod incidunt, odio
              praesentium aperiam eveniet.
            </p>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Voluptate, culpa ex quisquam eum doloremque provident unde vitae?
              Sunt odio laborum architecto sint excepturi quasi tempore eveniet
              molestiae officia possimus ex, omnis incidunt in enim ut modi
              quisquam? Ipsa, aliquam.
            </p>
          </div>
        </div>
      </Layout>
    </>
  );
}
