import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Category from "../components/Category";
import { useRouter } from "next/router";
import Link from "next/link";

import slide3 from "../assets/img/bg-img/3.jpg";
import slide4 from "../assets/img/bg-img/4.jpg";
import slide5 from "../assets/img/bg-img/5.jpg";
import slide6 from "../assets/img/bg-img/6.jpg";
import slide7 from "../assets/img/bg-img/7.jpg";
import slide8 from "../assets/img/bg-img/8.jpg";
import slide9 from "../assets/img/bg-img/9.jpg";
import slide10 from "../assets/img/bg-img/10.jpg";
import slide11 from "../assets/img/bg-img/11.jpg";

export default function Trending() {
  const router = useRouter();
  const categories = [
    {
      id: 1,
      category: "Business",
      image: slide3.src,
    },
    {
      id: 2,
      category: "Business",
      image: slide3.src,
    },
    {
      id: 3,
      category: "Business",
      image: slide3.src,
    },
  ];
  return (
    <>
      <Head>
        <title>Trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Trending">
        <div className="trending-news-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between">
              <h5 className="mb-3 newsten-title">Trending</h5>
              <p className="mb-3 line-height-1">{categories.length} Posts</p>
            </div>
          </div>
          <div className="container">
            {categories.map((item) => {
              return (
                <div className="single-trending-post d-flex" key={item.id}>
                  <div className="post-thumbnail">
                    <Image src={slide4.src} alt="" />
                  </div>
                  <div className="post-content">
                    <Link className="post-title" href="single.html">
                      Swimming is a good exercise for the body
                    </Link>
                    <div className="post-meta d-flex align-items-center">
                      <Link href="#">Sports</Link>
                      <Link href="#">02 Jun 20</Link>
                    </div>
                  </div>
                </div>
              );
            })}

            {/* <!-- Single Trending Post--> */}
          </div>
          <div className="container">
            <div className="text-center mt-3">
              <Link className="btn btn-primary" href="#">
                Load More
              </Link>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
