import React from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Category from "../components/Category";
import { useRouter } from "next/router";
import Link from "next/link";
import axios from "axios";
import moment from "moment";
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from "reactstrap";
import PostCard from "../components/PostCard";
export default function Trending(props) {
  const [modal, setModal] = React.useState(false);
  const [singleContent, setSingleContent] = React.useState(null);

  const toggle = (item) => {
    setSingleContent(item); // setSingleContet(item)
    setModal(!modal);
  };
  const router = useRouter();
  // router.reload();
  return (
    <div>
      <Head>
        <title>Trending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal isOpen={modal} toggle={toggle}>
        <ModalHeader toggle={toggle}>Modal title</ModalHeader>
        <ModalBody>
          {singleContent !== null ? (
            <PostCard
              title={singleContent.title}
              image={singleContent.urlToImage}
              content={singleContent.content}
              date={singleContent.publishedAt}
            />
          ) : null}
        </ModalBody>

        <ModalFooter>
          <Button color="primary" onClick={toggle}>
            Do Something
          </Button>{" "}
          <Button color="secondary" onClick={toggle}>
            Cancel
          </Button>
        </ModalFooter>
      </Modal>
      <Layout title="Trending">
        <div className="trending-news-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between">
              <h5 className="mb-3 newsten-title">Trending</h5>
              <p className="mb-3 line-height-1">{5} Posts</p>
            </div>
          </div>
          <div className="container">
            {props.news.map((item, index) => {
              return (
                <div className="single-trending-post d-flex" key={index}>
                  <div className="post-thumbnail">
                    <img src={item.urlToImage} alt="" width={300} height={230}/>
                  </div>
                  <div className="post-content">
                    <a className="post-title" onClick={()=>toggle(item)}> 
                      {item.title}
                    </a>
                    <div className="post-meta d-flex align-items-center">
                      {/* <Link href="#">{moment.fromNow(item.publishedAt)}</Link> */}
                      <Link href="#"><a>{item.author}</a></Link>
                    </div>
                  </div>
                </div>
              );
            })}

            {/* <!-- Single Trending Post--> */}
          </div>
          <div className="container">
            <div className="text-center mt-3">
              <Link  href="#">
                <a className="btn btn-primary">load More</a>
              </Link>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
 
export async function getServerSideProps(context) {
  const trial = async () => {
    let result = await axios.get(
      `https://t1ti0k29ig.execute-api.us-east-1.amazonaws.com/dev/?topic=world`
    );
    return result.data;
  };
  const config = await trial();
  const news = config.message.articles;

  return {
    props: {
      news,
      // categories,
    },
  };
}
