import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../../components/Layout";
import Category from "../../components/Category";
import { useRouter } from "next/router";
import Link from "next/link";

import slide3 from "../../assets/img/bg-img/3.jpg";
import slide4 from "../../assets/img/bg-img/4.jpg";

export default function CategoryId() {
  const router = useRouter();
  const { name } = router.query;
  const categories = [
    {
      id: 1,
      category: "Business",
      image: slide3.src,
    },
    {
      id: 2,
      category: "Business",
      image: slide3.src,
    },
    {
      id: 3,
      category: "Business",
      image: slide3.src,
    },
  ];
  return (
    <>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title={name}>
        <div className="trending-news-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between">
              <h5 className="mb-3 newsten-title">{name}</h5>
              <p className="mb-3 line-height-1">{categories.length} Posts</p>
            </div>
          </div>
          <div className="container">
            {categories.map((item) => {
              return (
                <div className="single-trending-post d-flex" key={item.id}>
                  <div className="post-thumbnail">
                    <Image src={slide4.src} alt="" />
                  </div>
                  <div className="post-content">
                    <Link className="post-title" href="/post">
                      Swimming is a good exercise for the body
                    </Link>
                    <div className="post-meta d-flex align-items-center">
                      <Link href="category/sport">Sports</Link>
                      {/* <Link href="">02 Jun 20</Link> */}
                    </div>
                  </div>
                </div>
              );
            })}

            {/* <!-- Single Trending Post--> */}
          </div>
          <div className="container">
            <div className="text-center mt-3">
              <Link className="btn btn-primary" href="category/post">
                Load More
              </Link>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

{
  /* <div className="single-trending-post d-flex">
<div className="post-thumbnail"><Image src="img/bg-img/17.jpg" alt=""/></div>
<div className="post-content"><Link className="post-title" href="single.html">Some tips for taking care of the body this summer</Link>
  <div className="post-meta d-flex align-items-center"><Link href="#">Fashion</Link><Link href="#">04 Jun 20</Link></div>
</div> */
}
