import React from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../../components/Layout";
import Category from "../../components/Category";
import { useRouter } from "next/router";
import Link from "next/link";
import axios from "axios";
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from "reactstrap";
import PostCard from "../../components/PostCard";

export default function CategoryId(props) {
  const [modal, setModal] = React.useState(false);
  const [singleContent, setSingleContent] = React.useState(null);

  const toggle = (item) => {
    setSingleContent(item); // setSingleContet(item)
    setModal(!modal);
  };
  const router = useRouter();
  const { name } = router.query;
  return (
    <>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal isOpen={modal} toggle={toggle} >
        <ModalHeader toggle={toggle}>Modal title</ModalHeader>
        <ModalBody>
          {singleContent !== null ? (
            <PostCard
              title={singleContent.title}
              image={singleContent.urlToImage}
              content={singleContent.content}
              date={singleContent.publishedAt}
            />
          ) : null}
        </ModalBody>

        <ModalFooter>
          <Button color="primary" onClick={toggle}>
            Do Something
          </Button>{" "}
          <Button color="secondary" onClick={toggle}>
            Cancel
          </Button>
        </ModalFooter>
      </Modal>
      <Layout title={name}>
        <div className="trending-news-wrapper">
          <div className="container">
            <div className="d-flex align-items-center justify-content-between">
              <h5 className="mb-3 newsten-title">{name}</h5>
              <p className="mb-3 line-height-1">{props.news.length} Posts</p>
            </div>
          </div>
          <div className="container">
            {props.news.map((item) => {
              return (
                <div className="single-trending-post d-flex" key={item.url}>
                  <div className="post-thumbnail">
                    <img src={item.urlToImage} alt="" />
                  </div>
                  <div className="post-content">
                    <Link href="#">
                      <a className="post-title" onClick={() => toggle(item)}>
                        {item.title}
                      </a>
                    </Link>
                    <div className="post-meta d-flex align-items-center">
                      <Link href="#">{name}</Link>
                      {/* <Link href="">02 Jun 20</Link> */}
                    </div>
                  </div>
                </div>
              );
            })}

            {/* <!-- Single Trending Post--> */}
          </div>
          <div className="container">
            <div className="text-center mt-3">
              <Link className="btn btn-primary" href="category/post">
                Load More
              </Link>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  // const session = await getSession(context);
  // if (!session) {
  //   return {
  //     props: {},
  //     redirect: {
  //       destination: '/login',
  //       permanent: false
  //     }
  //   };
  // }
  // const token = session?.accessToken;
  // const id = context.params.id;
  const trial = async () => {
    let result = await axios.get(
      `https://t1ti0k29ig.execute-api.us-east-1.amazonaws.com/dev/?category=${context.params.name}`
    );
    return result.data;
  };
  const config = await trial();
  const news = config.message.articles;

  return {
    props: {
      news,
    },
  };
}
