import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../../components/Layout";
import CategoryCard from "../../components/CategoryCard"

import slide3 from "../../assets/img/bg-img/3.jpg";
import slide7 from "../../assets/img/bg-img/7.jpg";
import slide8 from "../../assets/img/bg-img/8.jpg";
import slide9 from "../../assets/img/bg-img/9.jpg";

export default function Category() {
  const categories = [
    {
      id: 1,
      category: "Business",
      image: slide3.src,
      url:"/category/business"
    },
    {
      id: 2,
      category: "Politic",
      image: slide7.src,
      url:"/category/politics"
    },
    {
      id: 3,
      category: "Sports",
      image: slide8.src,
      url:"/category/sport"
    },

    {
      id: 4,
      category: "fashion",
      image: slide9.src,
      url:"/category/business"
    }
  ]
  return (
    <>
      <Head>
        <title>Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Category">
      <div className="all-catagory-wrapper">
        <div className="container">
          <h5 className="mb-3 newsten-title">All Catagory</h5>
        </div>
        <div className="container">
          <div className="row">
            {
              categories.map((item) => {
                return (
                  <CategoryCard key={item.id} {...item} />
                )
              })
            }
          </div>
        </div>
      </div>
      </Layout>
    </>
  );
}
