import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../../components/Layout";
import BookmarkCard from "../../components/BookmarkCard";
import {useRouter} from "next/router";

export default function Category(props) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>News Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Categories">
        <div className="all-catagory-wrapper">
          <div className="container">
            <h5 className="mb-3 newsten-title">#categories</h5>
          </div>
          <div className="container">
            <div className="row">
              {props.categories.map((item) => {
                return (
                   <BookmarkCard key={item.url} url={`/category/${item.category}`} category={item.category} image={item.image} title={item.title}/>
                );
              })}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}

export async function getServerSideProps(context) {
  // const session = await getSession(context);
  // if (!session) {
  //   return {
  //     props: {},
  //     redirect: {
  //       destination: '/login',
  //       permanent: false
  //     }
  //   };
  // }
  // const token = session?.accessToken;
  // const id = context.params.id;
 

  const categories = [
    {
      "id": 1,
     " category": "Fashion",
      "image": 'https://static.onecms.io/wp-content/uploads/sites/14/2020/07/15/fashion-header-1-2000.jpg',
      "title": "Follow the trends in fashion and life style",
      "url": "/category/fashion",
    },
    {
      "id": 2,
     " category": "Technology",
      "image": "https://i0.wp.com/businessday.ng/wp-content/uploads/2021/09/Tech.jpg",
      "title": "Technology and gadgets",
      "url": "/category/technology",
    },
    {
      "id": 3,
     " category": "Sports",
      "image": "https://sportsscoopaction.files.wordpress.com/2019/07/sport-set.png",
      url: "/category/sport",
    },
  
    {
      "id": 4,
     " category": "Politics",
      "image": 'https://www.vanguardngr.com/wp-content/uploads/2020/08/Politics.jpg',
      "url": "/category/politics",
      "title": "Follow all political news from every angle",
    },
  ];
  return {
    props: {
      // news,
      categories,
    },
  };
}